### ISSUE TITLE
How to add an element with class to the document?

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/html-rearranger#1]
I'm trying to get the first half of the project but failing so far and would appreciate a little help. 

I wanted to create an h2 heading and a list, then assign classes to them as 'below-ground' and 'above-ground' but couldn't make it work. Is this the right direction or is there an easier/ better way? 

I thought the second part of the project would keep me busy but am already struggling with this part :(

// Create a heading: “Below ground veggies”.
// Create a list to hold the below ground veggies.
// Add the heading and list to the document.
// Create a second heading for “Above ground veggies” and add it to the document.
// Create a list to hold the above ground veggies and add it to the document.

```
var $h2 = $('<h2>');
$h2.addClass('.below-ground-heading').html('Below ground veggies');
$h2.addClass('.above-ground-heading').html('Above ground veggies');

var $ul = $('<ul>');
$ul.addClass('.below-ground-list');
$ul.addClass('.above-ground-list');
```
@thomasjbradley

**Comment by C-G-G** [comment]
Then I continued as below:

// Loop over the veggies that exist in the HTML currently and add them to the appropriate list
```
$('li').each(function () {
  if ($(this).hasClass('below')) {
    $('.below-ground-list').append($(this));
  } else {
    $('.above-ground-list').append($(this));
  }
});
```

**Comment by thomasjbradley** [comment]
```js
var $h2 = $('<h2>');
$h2.addClass('.below-ground-heading').html('Below ground veggies');
```

This is correct! But you forgot to add it to the HTML page, with this:

```js
$('body').append($h2);
```

```js
$h2.addClass('.above-ground-heading').html('Above ground veggies');
```

This line is technically correct, but is reusing the original `$h2` which, is therefore, replacing its content.
You’d need to make a new `<h2>` variable first.
